spring:
  application:
    name: MutsaMiniProject
  datasource:
    url: jdbc:postgresql://svc.sel5.cloudtype.app:31799/myDB
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver
server:
    port: 9900